# Generated by Django 3.2.8 on 2021-10-19 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_geeksmodel_bal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geeksmodel',
            name='bal',
        ),
    ]
