# Generated by Django 3.2.8 on 2021-10-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_remove_geeksmodel_bal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geeksmodel',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='image_2',
            field=models.ImageField(default=8, upload_to='pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='image_link_1',
            field=models.URLField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='image_link_2',
            field=models.URLField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geeksmodel',
            name='image_main',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
